title : Blogtopus
tagline: Testing out Ruhoh
author :
  name : Kevin Brock
  email : kevin@brockoleur.com
  github : brockoleur
  twitter : brocktopus

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
